### ISSUE TITLE
How is this different from libnss_extrausers?

### ISSUE THREAD

**Issue by Dr-Desty-Nova** [thkukuk/libnss_usrfiles#1]
From the description they seem to be doing the same thing.
See [here](https://packages.debian.org/de/sid/libnss-extrausers)

`useradd` utility even has `--extrausers` switch to support it natively.

Could you please clarify?

**Comment by thkukuk** [comment]
The description is pretty clear in the difference: libnss_extrausers only supports passwd, group and shadow, while libnss_usrfiles supports **all** NSS services. So libnss_extrausers is only a small subset of libnss_usrfiles

Else:
* libnss_usrfiles is older than libnss_extrausers
* libss_usrfiles supports all NSS services, not a small subset
* libnss_usrfiles is to read and merge static "databases" from /usr provided by the distributor with the one from /etc created by an admin

See https://en.opensuse.org/openSUSE:Packaging_UsrEtc

To be honest, I don't see an use case for libnss_extrafiles, which sense does it make to have a second, modifyable user database in /var, which is not useable by distributors and has the same update problems?
